// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT_ojWywA-gGT2HAhn2wFbqyddqk3q59s',
    appId: '1:539711029806:web:47ae216c824e697d83d5bf',
    messagingSenderId: '539711029806',
    projectId: 'tutorial-181d4',
    authDomain: 'tutorial-181d4.firebaseapp.com',
    databaseURL: 'https://tutorial-181d4-default-rtdb.firebaseio.com',
    storageBucket: 'tutorial-181d4.firebasestorage.app',
    measurementId: 'G-R434X919KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcJ1_LL9RX9IR5wlXJcqP5plVPAPWkaKA',
    appId: '1:539711029806:android:ac9cc7f7434eb6b883d5bf',
    messagingSenderId: '539711029806',
    projectId: 'tutorial-181d4',
    databaseURL: 'https://tutorial-181d4-default-rtdb.firebaseio.com',
    storageBucket: 'tutorial-181d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqCra0UXHzIyF8HjN4GnmUG-rrgMgp4NM',
    appId: '1:539711029806:ios:214e3aabcd06986f83d5bf',
    messagingSenderId: '539711029806',
    projectId: 'tutorial-181d4',
    databaseURL: 'https://tutorial-181d4-default-rtdb.firebaseio.com',
    storageBucket: 'tutorial-181d4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqCra0UXHzIyF8HjN4GnmUG-rrgMgp4NM',
    appId: '1:539711029806:ios:214e3aabcd06986f83d5bf',
    messagingSenderId: '539711029806',
    projectId: 'tutorial-181d4',
    databaseURL: 'https://tutorial-181d4-default-rtdb.firebaseio.com',
    storageBucket: 'tutorial-181d4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLogin',
  );
}
